# Generated by Django 5.2.14 on 2026-09-25 12:03

import core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_unify_company_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('iyzico', 'iyzico'), ('garanti', 'Garanti BBVA')], default='iyzico', max_length=20, verbose_name='Aktif sanal POS')),
                ('enabled', models.BooleanField(default=False, verbose_name='Kart ödemesi açık')),
                ('sandbox', models.BooleanField(default=True, verbose_name='Test ortamı (yalnızca personel)')),
                ('public_origin', models.URLField(default='https://reklamanaliz.net', help_text='Yalnızca HTTPS site kökü. Örnek: https://reklamanaliz.net', verbose_name='Dönüş adresinin site kökü')),
                ('iyzico_api_key', core.fields.EncryptedTextField(blank=True, default='', verbose_name='iyzico API anahtarı')),
                ('iyzico_secret_key', core.fields.EncryptedTextField(blank=True, default='', verbose_name='iyzico gizli anahtar')),
                ('garanti_merchant_id', models.CharField(blank=True, default='', max_length=30, verbose_name='Garanti üye işyeri numarası')),
                ('garanti_terminal_id', models.CharField(blank=True, default='', max_length=8, verbose_name='Garanti terminal numarası')),
                ('garanti_user_id', models.CharField(default='GARANTI', max_length=40, verbose_name='Garanti kullanıcı adı')),
                ('garanti_prov_user', models.CharField(default='PROVOOS', max_length=40, verbose_name='Garanti provizyon kullanıcısı')),
                ('garanti_prov_password', core.fields.EncryptedTextField(blank=True, default='', verbose_name='Garanti provizyon şifresi')),
                ('garanti_store_key', core.fields.EncryptedTextField(blank=True, default='', verbose_name='Garanti 3D güvenlik anahtarı')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sanal POS Ayarları',
                'verbose_name_plural': 'Sanal POS Ayarları',
            },
        ),
        migrations.AlterModelOptions(
            name='legalsitesettings',
            options={'verbose_name': 'Şirket, İletişim ve Banka Ayarları', 'verbose_name_plural': 'Şirket, İletişim ve Banka Ayarları'},
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Hesap sahibi'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='bank_iban',
            field=models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Havale bankası'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='bank_transfer_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Havale kontrol süresi (takvim günü)'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Mobil telefon'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='İkinci telefon'),
        ),
        migrations.AddField(
            model_name='legalsitesettings',
            name='trade_registry_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Ticaret sicil numarası'),
        ),
        migrations.CreateModel(
            name='HostedPaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('configuration', core.fields.EncryptedTextField()),
                ('token', core.fields.EncryptedTextField(blank=True, default='')),
                ('purchase_data', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_session', to='core.payment')),
            ],
            options={
                'verbose_name': 'Sanal POS İşlemi',
                'verbose_name_plural': 'Sanal POS İşlemleri',
            },
        ),
    ]
