# Generated by Django 5.2.14 on 2026-09-28 09:08

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_paymentgatewaysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_ads', 'Google Ads'), ('facebook', 'Meta Ads')], max_length=32, unique=True, verbose_name='Platform')),
                ('client_id', models.CharField(max_length=255, verbose_name='Uygulama / istemci kimliği')),
                ('client_secret', core.fields.EncryptedTextField(verbose_name='Uygulama gizli anahtarı')),
                ('developer_token', core.fields.EncryptedTextField(blank=True, default='', verbose_name='Google Ads geliştirici tokenı')),
                ('redirect_uri', models.URLField(max_length=500, verbose_name='OAuth dönüş adresi')),
                ('enabled', models.BooleanField(default=False, verbose_name='Bu uygulama ayarlarını kullan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entegrasyon Uygulaması',
                'verbose_name_plural': 'Entegrasyon Uygulama Ayarları',
            },
        ),
    ]
