# Generated by Django 5.2.14 on 2026-09-28 12:59

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_integrationapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationapplication',
            options={'verbose_name': 'Platform Ayarı', 'verbose_name_plural': 'Platform Ayarları'},
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Uygulama / istemci kimliği'),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='client_secret',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='Uygulama gizli anahtarı'),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Meta Ads (Facebook)'), ('google_ads', 'Google Ads'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('google_analytics', 'Google Analytics 4')], max_length=32, unique=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='redirect_uri',
            field=models.URLField(blank=True, max_length=500, verbose_name='OAuth dönüş adresi'),
        ),
    ]
