# Generated by Django 5.2.14 on 2026-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_expand_platform_application_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='local_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ad',
            name='local_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='local_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
