# Generated by Django 5.2.14 on 2026-10-05 07:33

import re
from datetime import date

from django.db import migrations, models


YOUTUBE_PRIVACY = (
    '<h2>8. YouTube kanal verileri</h2><p>'
    "YouTube bağlantısı, kullanıcının resmi Google OAuth 2.0 izin ekranında verdiği yetkiyle kurulur. "
    "Yalnızca youtube.readonly kapsamı kullanılır; seçilen kanalın kimliği, adı ve temel kanal istatistikleri alınır. "
    "Bu veriler bağlantı yönetimi ve kullanıcıya görünen raporlama için kullanılır. YouTube içerikleri değiştirilmez. "
    "Erişim ve yenileme belirteçleri şifreli saklanır. Veri saklama ve silme esasları bu politikadaki ilgili bölümler "
    "ve Veri Saklama / Veri Silme politikaları kapsamında uygulanır. Kullanıcı uygulamanın bağlantı yönetiminden "
    "veya Google Hesabı üçüncü taraf erişim ayarlarından yetkiyi kaldırabilir; silme taleplerini [[KVKK_EMAIL]] "
    "adresine iletebilir.</p>"
)


def remove_analytics_records(apps, schema_editor):
    database = schema_editor.connection.alias
    # Only the retired provider is removed; advertising providers are untouched.
    apps.get_model('core', 'AnalyticsProperty').objects.using(database).all().delete()
    apps.get_model('core', 'Platform').objects.using(database).filter(code='google_analytics').delete()
    apps.get_model('core', 'IntegrationApplication').objects.using(database).filter(provider='google_analytics').delete()
    documents = apps.get_model('core', 'LegalDocument').objects.using(database).filter(slug='gizlilik-politikasi')
    for document in documents:
        content, changed = re.subn(
            r'<h2>8\. YouTube ve Google Analytics 4 verileri</h2>\s*<p>.*?</p>',
            YOUTUBE_PRIVACY, document.content, flags=re.S,
        )
        if changed:
            document.content = content
            document.version = '1.2'
            document.effective_date = date(2026, 10, 5)
            document.save(using=database, update_fields=['content', 'version', 'effective_date'])
    # Flush deferred FK triggers before altering the tables in this transaction.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_local_display_names'),
    ]

    operations = [
        migrations.RunPython(remove_analytics_records),
        migrations.AlterUniqueTogether(
            name='analyticslandingpagemetric',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='analyticslandingpagemetric',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='analyticsproperty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='analyticsproperty',
            name='platform_account',
        ),
        migrations.RemoveField(
            model_name='analyticsproperty',
            name='platform_connection',
        ),
        migrations.RemoveField(
            model_name='analyticsproperty',
            name='user',
        ),
        migrations.AlterField(
            model_name='integrationapplication',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Meta Ads (Facebook)'), ('google_ads', 'Google Ads'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)')], max_length=32, unique=True, verbose_name='Platform'),
        ),
        migrations.DeleteModel(
            name='AnalyticsDailyMetric',
        ),
        migrations.DeleteModel(
            name='AnalyticsLandingPageMetric',
        ),
        migrations.DeleteModel(
            name='AnalyticsProperty',
        ),
    ]
