# Generated by Django 5.2.14 on 2026-10-06 12:41

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_correct_competitor_library_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSourceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google_ads', 'Google Ads'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=32, unique=True, verbose_name='Platform')),
                ('source', models.CharField(choices=[('searchapi', 'SearchApi reklam kütüphanesi'), ('graph', 'Meta resmi Ad Library API'), ('serpapi', 'SerpApi Google Ads Transparency'), ('tiktok_official', 'TikTok Commercial Content API')], max_length=32, verbose_name='Reklam kaynağı')),
                ('credential', core.fields.EncryptedTextField(blank=True, default='', verbose_name='API anahtarı / erişim tokenı')),
                ('countries', models.CharField(blank=True, default='', help_text='ISO ülke kodlarını virgülle ayırın: TR veya DE,FR. Boş bırakılırsa mevcut varsayılan kapsam kullanılır.', max_length=200, verbose_name='Ülkeler')),
                ('enabled', models.BooleanField(default=False, verbose_name='Rakip reklam çekimi etkin')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='Son bağlantı testi')),
                ('last_test_result', models.CharField(blank=True, default='', max_length=500, verbose_name='Son test sonucu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.competitor', verbose_name='Bağlantı testi için örnek rakip')),
            ],
            options={
                'verbose_name': 'Rakip Reklam Kaynağı',
                'verbose_name_plural': 'Rakip Reklam Kaynakları',
            },
        ),
    ]
