# Generated by Django 5.2.14 on 2026-10-07 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def retire_records(apps, schema_editor):
    from django.db.models import Q
    alias = schema_editor.connection.alias
    def rows(name):
        return apps.get_model('core', name).objects.using(alias)
    own_ids = set(rows('Ad').filter(source_type='OWN').values_list('pk', flat=True))
    rows('AnomalyAlert').filter(rakip__source_type='COMPETITOR').delete()
    rows('OctoTaskInstance').filter(Q(module='competitor') | Q(ad__source_type='COMPETITOR') | Q(rule__module='competitor')).delete()
    rows('OctoTaskRule').filter(module='competitor').delete()
    rows('CreativeProject').filter(Q(source_type='competitor_ad') | Q(source_competitor__isnull=False)).delete()
    rows('SocialPost').filter(competitor__isnull=False).delete()
    rows('RawDataSnapshot').filter(Q(competitor__isnull=False) | Q(source_type__in=['COMPETITOR','COMPETITOR_AD']) | Q(ad__source_type='COMPETITOR')).delete()
    rows('RawPlatformData').filter(data_type='COMPETITOR_AD').delete()
    rows('AIAnalysis').filter(analysis_type='competitor').delete()
    rows('AdMetricHistory').filter(is_competitor_snapshot=True).delete()
    rows('Ad').filter(source_type='COMPETITOR').delete()
    rows('ActivityLog').filter(action_type='competitor').delete()
    rows('AdminManagedCelerySchedule').filter(task_name__icontains='competitor').delete()
    rows('Notification').filter(Q(link__icontains='rakip') | Q(link__icontains='competitor') | Q(title__icontains='rakip')).delete()
    for name in ['ControlTowerCardSnapshot','ControlTowerAIAnalysis','ControlTowerActionItem']:
        rows(name).filter(card_key='competitor_intelligence').delete()
    rows('CompetitorSourceSetting').all().delete()
    rows('Competitor').all().delete()
    for plan in rows('MembershipPlan').all().iterator():
        features = '\n'.join(line for line in (plan.features or '').splitlines() if not any(word in line.lower() for word in ('rakip','competitor')))
        if features != plan.features:
            rows('MembershipPlan').filter(pk=plan.pk).update(features=features)
    for name in ['AgencyRoleGroup','OrganizationMember']:
        for record in rows(name).all().iterator():
            original = record.menu_permissions
            if isinstance(original, dict):
                cleaned = {k:v for k,v in original.items() if 'competitor' not in k and 'rakip' not in k}
            elif isinstance(original, list):
                cleaned = [v for v in original if not isinstance(v,str) or ('competitor' not in v and 'rakip' not in v)]
            else:
                continue
            if cleaned != original:
                rows(name).filter(pk=record.pk).update(menu_permissions=cleaned)

    retired_keys = {'competitor_ads','competitor','competitor_pressure','competitor_intelligence','competitors','competitor_groups'}
    def clean_payload(value, rename_advantage=False):
        if isinstance(value, dict):
            return {('value_proposition' if rename_advantage and key == 'competitive_advantage' else key): clean_payload(item, rename_advantage) for key,item in value.items() if key not in retired_keys}
        if isinstance(value, list):
            return [clean_payload(item, rename_advantage) for item in value if not (isinstance(item,dict) and any(word in str(item.get('name','')).lower() for word in ('rakip','rekabet','competitor')))]
        return value
    payload_fields = {
        'ControlTowerSnapshot': ['summary','decision_center'],
        'ControlTowerCardSnapshot': ['payload'],
        'ControlTowerAIAnalysis': ['payload'],
        'ReklamAIAnaliz': ['agents_results'],
        'CampaignOctoAnalysis': ['agents_payload','raw_ai_payload'],
        'CreativeProject': ['generated_variants'],
    }
    for name,fields in payload_fields.items():
        for record in rows(name).all().iterator():
            updates = {}
            for field in fields:
                original = getattr(record,field)
                cleaned = clean_payload(original, rename_advantage=name == 'CreativeProject')
                if cleaned != original:
                    updates[field] = cleaned
            if updates:
                rows(name).filter(pk=record.pk).update(**updates)
    if set(rows('Ad').filter(source_type='OWN').values_list('pk', flat=True)) != own_ids:
        raise RuntimeError('Own ads changed during retirement; transaction aborted.')
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SET CONSTRAINTS ALL IMMEDIATE')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_competitor_source_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(retire_records, reverse_code=None),
        migrations.RemoveIndex(
            model_name='socialpost',
            name='core_social_competi_1e4b83_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawdatasnapshot',
            name='core_rawdat_competi_bf845a_idx',
        ),
        migrations.RemoveField(
            model_name='rawdatasnapshot',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='competitor',
        ),
        migrations.RemoveIndex(
            model_name='admetrichistory',
            name='core_admetr_is_comp_ab1da3_idx',
        ),
        migrations.RemoveField(
            model_name='admetrichistory',
            name='is_competitor_snapshot',
        ),
        migrations.RemoveField(
            model_name='agencyrolegroup',
            name='can_manage_competitors',
        ),
        migrations.RenameField(
            model_name='anomalyalert',
            old_name='rakip',
            new_name='ad',
        ),
        migrations.RemoveField(
            model_name='campaignoctoanalysis',
            name='competitor_position',
        ),
        migrations.RemoveField(
            model_name='creativeproject',
            name='source_competitor',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='allow_manual_competitor_sync',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='competitor_auto_discovery',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='competitor_fetch_enabled',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='competitor_fetch_frequency',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='competitor_sync_interval_minutes',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='max_competitors',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='competitor_notifications',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='can_manage_competitors',
        ),
        migrations.RemoveField(
            model_name='reklamaianaliz',
            name='competitor_score',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='competitor',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('notification', 'Bildirim'), ('campaign', 'Kampanya'), ('ad', 'Reklam'), ('ai', 'AI'), ('optimization', 'Optimizasyon'), ('account', 'Hesap'), ('payment', 'Ödeme'), ('system', 'Sistem')], default='system', max_length=40),
        ),
        migrations.AlterField(
            model_name='ad',
            name='source_type',
            field=models.CharField(choices=[('OWN', 'Kendi Reklamım')], default='OWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='analysis_type',
            field=models.CharField(choices=[('campaign', 'Kampanya Analizi'), ('account', 'Hesap Analizi'), ('ad', 'Reklam Analizi')], default='campaign', max_length=50),
        ),
        migrations.AlterField(
            model_name='controltowercardsnapshot',
            name='card_key',
            field=models.CharField(choices=[('kpi_strip', 'KPI Strip'), ('decision_center', 'Octo Decision Center'), ('octo_task_center', 'Octo Task Center'), ('critical_alerts', 'Critical Alerts'), ('campaign_health', 'Campaign Health Center'), ('creative_wall', 'Creative Performance Wall'), ('platform_status', 'Platform Status Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='creativeproject',
            name='source_type',
            field=models.CharField(choices=[('my_ad', 'Kendi Reklamım'), ('trend', 'Trend Konu'), ('scratch', 'Sıfırdan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='octotaskrule',
            name='module',
            field=models.CharField(choices=[('performance', 'Performans'), ('creative', 'Kreatif'), ('budget', 'Bütçe'), ('conversion', 'Dönüşüm')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rawdatasnapshot',
            name='source_type',
            field=models.CharField(choices=[('ACCOUNT', 'Hesap'), ('CAMPAIGN', 'Kampanya'), ('ADGROUP', 'Reklam Grubu'), ('AD', 'Reklam'), ('CREATIVE', 'Kreatif'), ('METRIC', 'Metrik'), ('AUDIENCE', 'Kitle'), ('PLACEMENT', 'Yerleşim'), ('POST', 'Organik Paylaşım'), ('INSIGHT', 'İçgörü'), ('ERROR', 'Hata'), ('OTHER', 'Diğer')], db_index=True, default='OTHER', max_length=50, verbose_name='Kaynak Tipi'),
        ),
        migrations.AlterField(
            model_name='rawplatformdata',
            name='data_type',
            field=models.CharField(choices=[('CONNECTION', 'Bağlantı'), ('ACCOUNT', 'Hesap'), ('CAMPAIGN', 'Kampanya'), ('ADGROUP', 'Reklam Grubu'), ('AD', 'Reklam'), ('CREATIVE', 'Kreatif'), ('SOCIAL_POST', 'Sosyal Paylaşım'), ('METRIC', 'Metrik'), ('OTHER', 'Diğer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='core.platformaccount'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='core.platformconnection'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompetitorSourceSetting',
        ),
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
