# Generated by Django 5.2.14 on 2026-10-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_retire_competitor_features'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='core_ad_ad_libr_8d1dcc_idx',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='ad_library_id',
        ),
    ]
