[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python3.12 -m pip install -r requirements.txt"]

[start]
cmd = "cd instagram_reklam_analiz && celery -A config worker --loglevel=info"