"""Admin setup catalog; capability labels describe implemented application code."""

PLATFORM_SETUP = {
    "facebook": dict(name="Meta Ads (Facebook)", client_label="Meta Uygulama Kimliği (App ID)", secret_label="Meta App Secret", env="FACEBOOK_APP_ID", callback="/connect/facebook/callback/", mode="oauth", console="https://developers.facebook.com/apps/", docs="https://developers.facebook.com/docs/marketing-api/get-started/authorization/", instructions="Uygulama ayarları → Temel bölümünden App ID ve App Secret alın. Facebook Login dönüş adresini birebir ekleyin. Reklam hesabını okuyabilmek için ads_read izni gerekir; dış müşteriler için sağlayıcı onaylarını tamamlayın.", capability="Reklam hesabı OAuth bağlantısı ve kampanya okuma mevcut."),
    "google_ads": dict(name="Google Ads", client_label="Google OAuth İstemci Kimliği", secret_label="Google OAuth İstemci Gizli Anahtarı", env="GOOGLE_ADS_CLIENT_ID", callback="/connect/google-ads/callback/", mode="oauth", console="https://console.cloud.google.com/auth/clients", docs="https://developers.google.com/google-ads/api/docs/oauth/overview", instructions="Google Ads API'yi açın. Google Auth Platform'da Web application OAuth istemcisi oluşturun ve dönüş adresini ekleyin. Veri Erişimi bölümünde Google Ads kapsamını tanımlayın. Google Ads API Overview ekranından projenin üretim erişim seviyesini kontrol edin. 9 Eylül 2026'dan sonra yeni kurulumlarda geliştirici tokenı gerekmez.", capability="Reklam hesabı OAuth bağlantısı ve kampanya okuma mevcut."),
    "instagram": dict(name="Instagram", client_label="Instagram Uygulama Kimliği", secret_label="Instagram Uygulama Gizli Anahtarı", env="INSTAGRAM_APP_ID", callback="/connect/instagram/callback/", mode="oauth", console="https://developers.facebook.com/apps/", docs="https://developers.facebook.com/docs/instagram-platform/", instructions="Instagram Business Login uygulama bilgilerini girin. OAuth callback adresini Meta paneline ekleyin. instagram_business_basic ve instagram_business_manage_insights izinlerini onaylatın.", capability="Üye Instagram girişiyle hesabını otomatik bağlar; token girmesi gerekmez."),
    "youtube": dict(name="YouTube", client_label="YouTube Google OAuth İstemci Kimliği", secret_label="YouTube OAuth İstemci Gizli Anahtarı", env="YOUTUBE_CLIENT_ID", callback="/connect/youtube/callback/", mode="oauth", console="https://console.cloud.google.com/auth/clients", docs="https://developers.google.com/youtube/v3/guides/auth/server-side-web-apps", instructions="Ayrı Google Cloud projesinde YouTube Data API v3'ü etkinleştirin. Web OAuth istemcisine gösterilen dönüş adresini ekleyin. youtube.readonly iznini yapılandırın. Uzun süreli erişim için izin ekranının Testing durumunda kalmaması gerekir. YouTube reklamları Google Ads ile bağlanır.", capability="OAuth ile kanal seçimi, otomatik token yenileme ve kanal istatistiklerini okuma mevcut. Video yükleme ve YouTube Analytics raporları bu bağlantıya dahil değildir."),
    "tiktok": dict(name="TikTok", client_label="TikTok Client Key", secret_label="TikTok Client Secret", env="TIKTOK_CLIENT_KEY", callback="", mode="draft", console="https://developers.tiktok.com/", docs="https://developers.tiktok.com/doc/login-kit-web/", instructions="TikTok Developers → Manage apps → Credentials bölümünden Client Key ve Client Secret alın. Login Kit ve gereken ürün izinlerini yapılandırın. Profil izni TikTok Ads erişimi sağlamaz; reklam API'si ayrı başvuru gerektirir.", capability="Tokenla profil doğrulaması mevcut. Bu ayarı kullanan OAuth ve reklam aktarımı henüz uygulanmadı."),
    "linkedin": dict(name="LinkedIn", client_label="LinkedIn Client ID", secret_label="LinkedIn Client Secret", env="LINKEDIN_CLIENT_ID", callback="", mode="draft", console="https://www.linkedin.com/developers/apps", docs="https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow", instructions="LinkedIn Developers → Uygulama → Auth bölümünden istemci bilgilerini alın. Gereken ürün ve erişim onaylarını tamamlayın. Profil erişimi Advertising API yetkisi değildir.", capability="Tokenla profil doğrulaması mevcut. Bu ayarı kullanan OAuth ve reklam aktarımı henüz uygulanmadı."),
    "x": dict(name="X (Twitter)", client_label="X OAuth 2.0 Client ID", secret_label="X OAuth 2.0 Client Secret", env="X_CLIENT_ID", callback="", mode="draft", console="https://console.x.com/", docs="https://docs.x.com/fundamentals/authentication/oauth-2-0/authorization-code", instructions="Uygulamanın User authentication ayarlarında OAuth 2.0 web uygulaması bilgilerini alın. API erişim planını kontrol edin. OAuth 1.0 API Key/Secret ile OAuth 2.0 Client ID/Secret farklıdır; reklam erişimi ayrıca gerekir.", capability="Tokenla profil doğrulaması mevcut. Bu ayarı kullanan OAuth ve reklam aktarımı henüz uygulanmadı."),
    "google_analytics": dict(name="Google Analytics 4", client_label="GA4 Google OAuth İstemci Kimliği", secret_label="GA4 OAuth İstemci Gizli Anahtarı", env="GOOGLE_ANALYTICS_CLIENT_ID", callback="/connect/google-analytics/callback/", mode="oauth", console="https://console.cloud.google.com/auth/clients", docs="https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries", instructions="Ayrı Google Cloud projesinde Google Analytics Data API ve Admin API'yi etkinleştirin. Web OAuth istemcisine gösterilen dönüş adresini ekleyin; analytics.readonly iznini yapılandırın. Mülk ID'sini Client ID alanına yazmayın. Uzun süreli erişim için izin ekranı Testing durumunda kalmamalıdır.", capability="OAuth ile GA4 mülk seçimi, otomatik token yenileme ve günlük / açılış sayfası rapor aktarımı mevcut."),
}

PLATFORM_CHOICES = [(code, spec["name"]) for code, spec in PLATFORM_SETUP.items()]
